const { neon } = require("@neondatabase/serverless");
const crypto = require("crypto");

function db(){ if(!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not configured"); return neon(process.env.DATABASE_URL); }
function secret(){ if(!process.env.SESSION_SECRET) throw new Error("SESSION_SECRET is not configured"); return process.env.SESSION_SECRET; }
function sign(v){ return crypto.createHmac("sha256",secret()).update(v).digest("base64url"); }
function cookie(name,value,maxAge=60*60*24*7){ return `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`; }
function cookies(req){ return Object.fromEntries((req.headers.cookie||"").split(";").filter(Boolean).map(x=>{const i=x.indexOf("=");return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]})); }
function sessionUser(req){
 const raw=cookies(req).ds_session; if(!raw)return null;
 const [payload,sig]=raw.split("."); if(!payload||!sig)return null;
 const expected=sign(payload); if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;
 try{const u=JSON.parse(Buffer.from(payload,"base64url").toString());return u.exp&&u.exp>Date.now()?u:null}catch{return null}
}
function sessionCookie(user){const p=Buffer.from(JSON.stringify({id:user.id,login:user.login,avatar:user.avatar,exp:Date.now()+7*24*60*60*1000}),"utf8").toString("base64url");return cookie("ds_session",p+"."+sign(p));}
function json(res,status,data,headers={}){res.statusCode=status;Object.entries({"Content-Type":"application/json; charset=utf-8",...headers}).forEach(([k,v])=>res.setHeader(k,v));res.end(JSON.stringify(data));}
async function body(req){let s="";for await(const c of req)s+=c;return s?JSON.parse(s):{};}
function pathOf(req){return new URL(req.url,"http://localhost").pathname.replace(/^\/api\/?/,"").replace(/\/$/,"");}

async function health(req,res){if(req.method!=="GET")return json(res,405,{error:"Method not allowed"});try{await db()\`SELECT 1 AS ok\`;return json(res,200,{ok:true,service:"DevShowcase API",database:"connected",timestamp:new Date().toISOString()});}catch(e){return json(res,503,{ok:false,service:"DevShowcase API",database:"unavailable",error:"Database unavailable"});}}
function me(req,res){return json(res,200,{user:sessionUser(req)});}
async function activity(req,res){if(req.method!=="GET")return json(res,405,{error:"Method not allowed"});const sql=db();return json(res,200,{activity:await sql\`SELECT a.id,a.type,a.entity_id,a.message,a.created_at,u.login AS author,u.avatar FROM activity a JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 100\`});}

async function projects(req,res){
 const sql=db();
 if(req.method==="GET"){const rows=await sql\`SELECT p.id,p.name,p.description AS desc,p.category,p.github_url AS github,p.demo_url AS demo,p.tags,p.featured,p.stars AS views,p.forks,p.views AS real_views,(SELECT count(*) FROM project_likes l WHERE l.project_id=p.id) AS likes,u.id AS author_id,u.login AS author,u.avatar FROM projects p LEFT JOIN users u ON u.id=p.author_id WHERE p.status='approved' ORDER BY p.featured DESC,p.created_at DESC LIMIT 200\`;return json(res,200,{projects:rows});}
 if(req.method==="POST"){const user=sessionUser(req);if(!user)return json(res,401,{error:"Sign in with GitHub before submitting a project"});const d=await body(req);if(!d.name||!d.github)return json(res,400,{error:"name and github are required"});try{const gh=new URL(String(d.github));if(gh.hostname!=="github.com"&&!gh.hostname.endsWith(".github.com"))return json(res,400,{error:"GitHub URL required"});}catch{return json(res,400,{error:"Invalid GitHub URL"})}const tags=Array.isArray(d.tags)?d.tags.filter(Boolean).slice(0,12):[];const rows=await sql\`INSERT INTO projects(name,description,category,github_url,demo_url,author_id,tags,status) VALUES(${String(d.name).slice(0,120)},${String(d.desc||"").slice(0,2000)},${String(d.category||"Open Source").slice(0,80)},${String(d.github)},${d.demo?String(d.demo):null},${user.id},${JSON.stringify(tags)}::jsonb,'pending') ON CONFLICT(github_url) DO NOTHING RETURNING id,name,status\`;if(!rows.length)return json(res,409,{error:"That GitHub repository is already submitted"});return json(res,201,{project:rows[0],message:"Submitted for moderation"});}
 return json(res,405,{error:"Method not allowed"});
}

async function project(req,res){const sql=db(),id=Number(new URL(req.url,"http://x").searchParams.get("id"));if(!id)return json(res,400,{error:"id required"});if(req.method==="POST"){const u=sessionUser(req);if(!u)return json(res,401,{error:"Sign in required"});await sql\`UPDATE projects SET views=views+1 WHERE id=${id} AND status='approved'\`;return json(res,200,{ok:true});}if(req.method==="GET"){const r=await sql\`SELECT p.id,p.name,p.description AS desc,p.category,p.github_url AS github,p.demo_url AS demo,p.tags,p.featured,p.stars AS views,p.forks,p.views AS real_views,(SELECT count(*) FROM project_likes l WHERE l.project_id=p.id) AS likes,u.login AS author,u.avatar FROM projects p LEFT JOIN users u ON u.id=p.author_id WHERE p.id=${id} AND p.status='approved'\`;return r[0]?json(res,200,{project:r[0]}):json(res,404,{error:"Project not found"});}return json(res,405,{error:"Method not allowed"});}

async function profile(req,res){const sql=db(),login=String(new URL(req.url,"http://x").searchParams.get("login")||"").trim();if(!login)return json(res,400,{error:"login required"});const rows=await sql\`SELECT u.id,u.login,u.avatar,u.bio,u.website,(SELECT count(*) FROM follows f WHERE f.following_id=u.id) AS followers,(SELECT count(*) FROM follows f WHERE f.follower_id=u.id) AS following FROM users u WHERE lower(u.login)=lower(${login}) LIMIT 1\`;if(!rows[0])return json(res,404,{error:"Profile not found"});const projects=await sql\`SELECT p.id,p.name,p.description AS desc,p.category,p.github_url AS github,p.demo_url AS demo,p.tags,p.featured,p.stars AS views,p.forks,p.views AS real_views,(SELECT count(*) FROM project_likes l WHERE l.project_id=p.id) AS likes FROM projects p WHERE p.author_id=${rows[0].id} AND p.status='approved' ORDER BY p.created_at DESC LIMIT 50\`;const u=sessionUser(req);let following=false;if(u)following=!!(await sql\`SELECT 1 FROM follows f WHERE f.follower_id=${u.id} AND f.following_id=${rows[0].id}\`)[0];return json(res,200,{profile:rows[0],following,projects});}

async function social(req,res){const sql=db(),u=sessionUser(req);if(!u)return json(res,401,{error:"Sign in with GitHub required"});if(req.method!=="POST")return json(res,405,{error:"POST only"});const d=await body(req),type=String(d.type||"");if(type==="follow"){const target=Number(d.userId);if(!target||target===Number(u.id))return json(res,400,{error:"Invalid user"});await sql\`INSERT INTO follows(follower_id,following_id) VALUES(${u.id},${target}) ON CONFLICT DO NOTHING\`;await sql\`INSERT INTO notifications(user_id,actor_id,type,entity_id,message) VALUES(${target},${u.id},'follow',${u.id},'started following you')\`;return json(res,200,{ok:true});}if(type==="unfollow"){await sql\`DELETE FROM follows WHERE follower_id=${u.id} AND following_id=${Number(d.userId)}\`;return json(res,200,{ok:true});}if(type==="like"){await sql\`INSERT INTO project_likes(user_id,project_id) VALUES(${u.id},${Number(d.projectId)}) ON CONFLICT DO NOTHING\`;return json(res,200,{ok:true});}if(type==="unlike"){await sql\`DELETE FROM project_likes WHERE user_id=${u.id} AND project_id=${Number(d.projectId)}\`;return json(res,200,{ok:true});}return json(res,400,{error:"Unknown social action"});}

async function notifications(req,res){const u=sessionUser(req);if(!u)return json(res,401,{error:"Sign in required"});const sql=db();if(req.method==="GET")return json(res,200,{notifications:await sql\`SELECT id,type,message,read,created_at FROM notifications WHERE user_id=${u.id} ORDER BY created_at DESC LIMIT 50\`});if(req.method==="PATCH"){await sql\`UPDATE notifications SET read=true WHERE user_id=${u.id}\`;return json(res,200,{ok:true});}return json(res,405,{error:"Method not allowed"});}

async function comments(req,res){const sql=db(),u=sessionUser(req),q=new URL(req.url,"http://x").searchParams;if(req.method==="GET"){const id=Number(q.get("discussionId"));if(!id)return json(res,400,{error:"discussionId required"});return json(res,200,{comments:await sql\`SELECT c.id,c.message,c.created_at,u.login AS author,u.avatar FROM discussion_comments c JOIN users u ON u.id=c.author_id WHERE c.discussion_id=${id} ORDER BY c.created_at ASC\`});}if(req.method==="POST"){if(!u)return json(res,401,{error:"Sign in with GitHub required"});const d=await body(req),id=Number(d.discussionId);if(!id||!d.message)return json(res,400,{error:"discussionId and message are required"});const x=await sql\`INSERT INTO discussion_comments(discussion_id,author_id,message) VALUES(${id},${u.id},${String(d.message).slice(0,3000)}) RETURNING id\`;const owner=await sql\`SELECT author_id FROM discussions WHERE id=${id}\`;if(owner[0]&&Number(owner[0].author_id)!==Number(u.id))await sql\`INSERT INTO notifications(user_id,actor_id,type,entity_id,message) VALUES(${owner[0].author_id},${u.id},'comment',${id},'commented on your discussion')\`;return json(res,201,{id:x[0].id});}return json(res,405,{error:"Method not allowed"});}

async function community(req,res){const sql=db(),user=sessionUser(req),q=new URL(req.url,"http://x").searchParams,type=q.get("type");if(req.method==="GET"){if(!type){return json(res,200,{discussions:await sql\`SELECT d.id,d.title,d.message,d.topic,d.project_url AS project,d.created_at,u.login AS author,u.avatar FROM discussions d JOIN users u ON u.id=d.author_id WHERE d.status='published' ORDER BY d.created_at DESC LIMIT 50\`});}if(type==="opportunities")return json(res,200,{opportunities:await sql\`SELECT o.*,u.login AS author,u.avatar FROM opportunities o LEFT JOIN users u ON u.id=o.author_id WHERE o.status='published' ORDER BY o.created_at DESC LIMIT 100\`});if(type==="resources")return json(res,200,{resources:await sql\`SELECT r.*,u.login AS author,u.avatar FROM resources r LEFT JOIN users u ON u.id=r.author_id ORDER BY r.created_at DESC LIMIT 100\`});if(type==="events")return json(res,200,{events:await sql\`SELECT e.*,u.login AS author,u.avatar,(SELECT count(*) FROM event_attendees a WHERE a.event_id=e.id) AS attendees FROM events e LEFT JOIN users u ON u.id=e.author_id ORDER BY e.starts_at NULLS LAST,e.created_at DESC LIMIT 100\`});if(type==="mentors")return json(res,200,{mentors:await sql\`SELECT u.id,u.login,u.avatar,u.bio,u.website,mp.headline,mp.expertise,mp.availability,mp.profile_url FROM mentor_profiles mp JOIN users u ON u.id=mp.user_id ORDER BY mp.updated_at DESC LIMIT 100\`});return json(res,400,{error:"Unknown community type"});}
 if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});if(!user)return json(res,401,{error:"Sign in with GitHub required"});const d=await body(req);
 if(!type){if(!d.title||!d.message)return json(res,400,{error:"title and message are required"});const x=await sql\`INSERT INTO discussions(author_id,title,message,topic,project_url) VALUES(${user.id},${String(d.title).slice(0,160)},${String(d.message).slice(0,5000)},${String(d.topic||"General").slice(0,80)},${d.project?String(d.project).slice(0,500):null}) RETURNING id\`;await sql\`INSERT INTO activity(user_id,type,entity_id,message) VALUES(${user.id},'discussion',${x[0].id},'started a discussion')\`;return json(res,201,{id:x[0].id});}
 if(type==="opportunities"){if(!d.title||!d.description)return json(res,400,{error:"title and description are required"});const rows=await sql\`INSERT INTO opportunities(author_id,title,type,level,description,url) VALUES(${user.id},${String(d.title).slice(0,160)},${String(d.type||"Open Source").slice(0,60)},${String(d.level||"All levels").slice(0,60)},${String(d.description).slice(0,3000)},${d.url?String(d.url).slice(0,500):null}) RETURNING *\`;return json(res,201,{opportunity:rows[0]});}
 if(type==="interest"){const id=Number(d.opportunity_id);if(!Number.isInteger(id)||id<1)return json(res,400,{error:"valid opportunity_id is required"});await sql\`INSERT INTO opportunity_interests(opportunity_id,user_id) VALUES(${id},${user.id}) ON CONFLICT DO NOTHING\`;return json(res,201,{ok:true});}
 if(type==="resources"){if(!d.title||!d.url)return json(res,400,{error:"title and url are required"});const rows=await sql\`INSERT INTO resources(author_id,title,description,url,category) VALUES(${user.id},${String(d.title).slice(0,160)},${String(d.description||"").slice(0,3000)},${String(d.url).slice(0,1000)},${String(d.category||"Learning").slice(0,60)}) RETURNING *\`;return json(res,201,{resource:rows[0]});}
 if(type==="events"){if(!d.title)return json(res,400,{error:"title is required"});const starts=d.starts_at?new Date(d.starts_at):null;if(starts&&!Number.isFinite(starts.getTime()))return json(res,400,{error:"starts_at must be a valid date"});const rows=await sql\`INSERT INTO events(author_id,title,description,starts_at,url) VALUES(${user.id},${String(d.title).slice(0,160)},${String(d.description||"").slice(0,3000)},${starts},${d.url?String(d.url).slice(0,1000):null}) RETURNING *\`;return json(res,201,{event:rows[0]});}
 if(type==="mentor"){await sql\`INSERT INTO mentor_profiles(user_id,headline,expertise,availability,profile_url) VALUES(${user.id},${String(d.title||"Community Mentor").slice(0,160)},${String(d.tech||"").slice(0,500)},'Open to requests',${d.url?String(d.url).slice(0,500):null}) ON CONFLICT(user_id) DO UPDATE SET headline=EXCLUDED.headline,expertise=EXCLUDED.expertise,profile_url=EXCLUDED.profile_url,updated_at=now()\`;return json(res,201,{ok:true,mentor:true});}
 if(type==="collaborate"){if(!d.title||!d.message)return json(res,400,{error:"title and message are required"});const rows=await sql\`INSERT INTO collaboration_requests(requester_id,title,message,technology,url) VALUES(${user.id},${String(d.title).slice(0,160)},${String(d.message).slice(0,3000)},${String(d.tech||"").slice(0,500)},${d.url?String(d.url).slice(0,500):null}) RETURNING *\`;await sql\`INSERT INTO activity(user_id,type,entity_id,message) VALUES(${user.id},'collaboration',${rows[0].id},'created a collaboration request')\`;return json(res,201,{request:rows[0]});}
 if(type==="mentorship"){const mentorId=Number(d.mentor_id);if(!Number.isInteger(mentorId)||mentorId<1)return json(res,400,{error:"valid mentor_id is required"});if(mentorId===Number(user.id))return json(res,400,{error:"You cannot request mentorship from yourself"});const rows=await sql\`INSERT INTO mentorship_requests(requester_id,mentor_id,topic,message) VALUES(${user.id},${mentorId},${String(d.topic||"General").slice(0,120)},${String(d.message||"").slice(0,3000)}) RETURNING *\`;return json(res,201,{request:rows[0]});}
 return json(res,400,{error:"Unsupported community type"});
}

async function adminProjects(req,res){const user=sessionUser(req);if(!user||!process.env.ADMIN_GITHUB_LOGINS?.split(",").map(x=>x.trim()).includes(user.login))return json(res,403,{error:"Admin access required"});const sql=db();if(req.method==="GET")return json(res,200,{projects:await sql\`SELECT p.*,u.login AS author FROM projects p LEFT JOIN users u ON u.id=p.author_id ORDER BY p.created_at DESC LIMIT 500\`});if(req.method==="PATCH"){const d=await body(req);if(!d.id||!["approved","rejected","pending"].includes(d.status))return json(res,400,{error:"id and valid status required"});const rows=await sql\`UPDATE projects SET status=${d.status},featured=COALESCE(${d.featured},featured),updated_at=now() WHERE id=${d.id} RETURNING id,status,featured\`;return json(res,200,{project:rows[0]});}return json(res,405,{error:"Method not allowed"});}

async function authGithub(req,res){if(req.method!=="GET")return json(res,405,{error:"GET required"});if(!process.env.GITHUB_CLIENT_ID||!process.env.APP_URL)return json(res,500,{error:"GITHUB_CLIENT_ID and APP_URL are required"});const state=crypto.randomUUID();res.setHeader("Set-Cookie",`ds_oauth=${state}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=600`);const u=new URL("https://github.com/login/oauth/authorize");u.searchParams.set("client_id",process.env.GITHUB_CLIENT_ID);u.searchParams.set("redirect_uri",process.env.APP_URL+"/api/auth/github/callback");u.searchParams.set("scope","read:user user:email");u.searchParams.set("state",state);res.statusCode=302;res.setHeader("Location",u.toString());res.end();}
async function authCallback(req,res){try{const c=cookies(req),q=new URL(req.url,"http://x").searchParams,code=q.get("code"),state=q.get("state");if(!code||!state||c.ds_oauth!==state)return json(res,400,{error:"Invalid OAuth state"});const tokenRes=await fetch("https://github.com/login/oauth/access_token",{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify({client_id:process.env.GITHUB_CLIENT_ID,client_secret:process.env.GITHUB_CLIENT_SECRET,code})});const token=await tokenRes.json();if(!token.access_token)throw new Error("GitHub OAuth failed");const gh=await fetch("https://api.github.com/user",{headers:{Authorization:"Bearer "+token.access_token,Accept:"application/vnd.github+json","User-Agent":"DevShowcase"}});const u=await gh.json();if(!u.id)throw new Error("Unable to read GitHub profile");const sql=db();const rows=await sql\`INSERT INTO users(github_id,login,avatar) VALUES(${String(u.id)},${u.login},${u.avatar_url||null}) ON CONFLICT(github_id) DO UPDATE SET login=EXCLUDED.login,avatar=EXCLUDED.avatar,updated_at=now() RETURNING id,login,avatar\`;res.setHeader("Set-Cookie",[sessionCookie(rows[0]),cookie("ds_oauth","",0)]);res.statusCode=302;res.setHeader("Location",process.env.APP_URL+"/");res.end();}catch(e){json(res,500,{error:e.message});}}
function logout(req,res){res.setHeader("Set-Cookie",cookie("ds_session","",0));res.statusCode=302;res.setHeader("Location","/");res.end();}

async function dbInit(req,res){if(req.method!=="POST")return json(res,405,{error:"POST required"});const expected=process.env.DB_INIT_SECRET;if(!expected)return json(res,503,{error:"DB initialization is disabled until DB_INIT_SECRET is configured"});if((req.headers["x-db-init-secret"]||"").toString()!==expected)return json(res,401,{error:"Unauthorized"});try{const sql=db();const statements=[
"CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, github_id TEXT UNIQUE NOT NULL, login TEXT NOT NULL, avatar TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS projects (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', category TEXT NOT NULL DEFAULT 'Open Source', github_url TEXT UNIQUE NOT NULL, demo_url TEXT, author_id BIGINT REFERENCES users(id) ON DELETE SET NULL, tags JSONB NOT NULL DEFAULT '[]'::jsonb, featured BOOLEAN NOT NULL DEFAULT false, status TEXT NOT NULL DEFAULT 'pending', stars INTEGER NOT NULL DEFAULT 0, forks INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS follows (follower_id BIGINT REFERENCES users(id) ON DELETE CASCADE, following_id BIGINT REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT now(), PRIMARY KEY(follower_id,following_id), CHECK(follower_id<>following_id))",
"CREATE TABLE IF NOT EXISTS project_likes (user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT now(), PRIMARY KEY(user_id,project_id))",
"CREATE TABLE IF NOT EXISTS discussions (id BIGSERIAL PRIMARY KEY, author_id BIGINT REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, message TEXT NOT NULL, topic TEXT NOT NULL DEFAULT 'General', project_url TEXT, status TEXT NOT NULL DEFAULT 'published', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS discussion_comments (id BIGSERIAL PRIMARY KEY, discussion_id BIGINT REFERENCES discussions(id) ON DELETE CASCADE, author_id BIGINT REFERENCES users(id) ON DELETE CASCADE, message TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS notifications (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL, type TEXT NOT NULL, entity_id BIGINT, message TEXT NOT NULL, read BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS activity (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, entity_id BIGINT, message TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS opportunities (id BIGSERIAL PRIMARY KEY, author_id BIGINT REFERENCES users(id) ON DELETE SET NULL, title TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'Open Source', level TEXT NOT NULL DEFAULT 'All levels', description TEXT NOT NULL DEFAULT '', url TEXT, status TEXT NOT NULL DEFAULT 'published', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS opportunity_interests (opportunity_id BIGINT REFERENCES opportunities(id) ON DELETE CASCADE, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT now(), PRIMARY KEY(opportunity_id,user_id))",
"CREATE TABLE IF NOT EXISTS mentorship_requests (id BIGSERIAL PRIMARY KEY, requester_id BIGINT REFERENCES users(id) ON DELETE CASCADE, mentor_id BIGINT REFERENCES users(id) ON DELETE CASCADE, topic TEXT NOT NULL DEFAULT 'General', message TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS resources (id BIGSERIAL PRIMARY KEY, author_id BIGINT REFERENCES users(id) ON DELETE SET NULL, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', url TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'Learning', created_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS events (id BIGSERIAL PRIMARY KEY, author_id BIGINT REFERENCES users(id) ON DELETE SET NULL, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', starts_at TIMESTAMPTZ, url TEXT, created_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS mentor_profiles (user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, headline TEXT NOT NULL DEFAULT '', expertise TEXT NOT NULL DEFAULT '', availability TEXT NOT NULL DEFAULT 'Open to requests', profile_url TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS collaboration_requests (id BIGSERIAL PRIMARY KEY, requester_id BIGINT REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, message TEXT NOT NULL DEFAULT '', technology TEXT NOT NULL DEFAULT '', url TEXT, status TEXT NOT NULL DEFAULT 'open', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now())",
"CREATE TABLE IF NOT EXISTS event_attendees (event_id BIGINT REFERENCES events(id) ON DELETE CASCADE, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT now(), PRIMARY KEY(event_id,user_id))",
"ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT ''","ALTER TABLE users ADD COLUMN IF NOT EXISTS website TEXT","ALTER TABLE projects ADD COLUMN IF NOT EXISTS views BIGINT NOT NULL DEFAULT 0",
"CREATE INDEX IF NOT EXISTS projects_status_idx ON projects(status)","CREATE INDEX IF NOT EXISTS projects_author_idx ON projects(author_id)","CREATE INDEX IF NOT EXISTS follows_following_idx ON follows(following_id)","CREATE INDEX IF NOT EXISTS discussions_created_idx ON discussions(created_at DESC)","CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications(user_id,read,created_at DESC)","CREATE INDEX IF NOT EXISTS activity_created_idx ON activity(created_at DESC)","CREATE INDEX IF NOT EXISTS opportunities_created_idx ON opportunities(created_at DESC)","CREATE INDEX IF NOT EXISTS mentorship_request_status_idx ON mentorship_requests(status)","CREATE INDEX IF NOT EXISTS resources_category_idx ON resources(category)","CREATE INDEX IF NOT EXISTS events_starts_idx ON events(starts_at)","CREATE INDEX IF NOT EXISTS mentor_profiles_expertise_idx ON mentor_profiles(expertise)","CREATE INDEX IF NOT EXISTS collaboration_requests_created_idx ON collaboration_requests(created_at DESC)"
];for(const s of statements)await sql.unsafe(s);return json(res,200,{ok:true,message:"Database initialized"});}catch(e){return json(res,500,{error:e.message});}}

async function router(req,res){
 try{
  const p=pathOf(req);
  if(p==="health")return await health(req,res);
  if(p==="me")return me(req,res);
  if(p==="activity")return await activity(req,res);
  if(p==="projects")return await projects(req,res);
  if(p==="project")return await project(req,res);
  if(p==="profile")return await profile(req,res);
  if(p==="social")return await social(req,res);
  if(p==="notifications")return await notifications(req,res);
  if(p==="community")return await community(req,res);
  if(p==="community/comments")return await comments(req,res);
  if(p==="admin/projects")return await adminProjects(req,res);
  if(p==="auth/github")return await authGithub(req,res);
  if(p==="auth/github/callback")return await authCallback(req,res);
  if(p==="auth/logout")return logout(req,res);
  if(p==="db/init")return await dbInit(req,res);
  return json(res,404,{error:"API route not found"});
 }catch(e){return json(res,500,{error:e.message||"Internal server error"});}
}
module.exports=router;
